# Generated by Django 5.1 on 2025-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('review_date', models.DateField()),
                ('employee_id', models.IntegerField()),
                ('reviewed_by', models.IntegerField()),
                ('review_period', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
